### ISSUE TITLE
Could you please update this library to the last version of Awesomium

### ISSUE THREAD

**Issue by renanpc** [David-Desmaisons/MVVM-for-awesomium#2]
Hello !

Could you update this library to the last version of awesomium, or at least the 1.7.5 version which counts with a lot of performance improvements.

Thanks.

**Comment by David-Desmaisons** [comment]
Hello @renanpc , I suggest you take a look at [Neutronium](https://github.com/NeutroniumCore/Neutronium) it offers an much improved version of MVVM-for-awesomium it is based on Chromium.Fx a binding to CEF (currently chromium version 56- versus 18 for Awesomium) and binding with both and vue.

**Comment by renanpc** [comment]
What happens is that I already have an application developed, it's possible to migrate from MVVMAwesomium to Neutronium without rewrite everything?

**Comment by David-Desmaisons** [comment]
The good news is that it should be pretty straight forward.
HTML, JS files and ViewModel can be reused without any modification. 
Obviously changes in XAML and application should be made but nothing complicated.
I can provide some guidance during the migration, if needed.

I am curious what is the application you are working on ?

**Comment by renanpc** [comment]
It's an software to manage a coin collector machine, the project started using MVVMAwesomium, but nowadays we're having some performance problems because of the HTML rendering engine, that's why I asked to update to de last version of awesomium, because the last version of awesomium has some performance improvements, but if you are saying that I can migrate to neutronium, I will be glad to do it.

**Comment by renanpc** [comment]
Well, I migrated everything to run with Neutronium, you were right I could reuse the most part of the project, I just needed to adapt some parts,  but it keep throwing an exception inside the method InjectInHtmlSession of BidirectionalMapper.

I'm using the cefglue browser rendering.

`
private async Task<IJavascriptObject> InjectInHtmlSession(IJsCsGlue root)
        {
            if (!Context.JavascriptFrameworkIsMappingObject)
                return root?.JsValue;

            if ((root == null) || (root.IsBasic()))
                return null;

            var jvm = _SessionCache.GetMapper(root as IJsCsMappedBridge);
            var res = _SessionInjector.Inject(root.JsValue, jvm);

            if ((root.CValue != null) && (res == null))
            {
                //KEEP THROWING THIS EXCEPTION
                throw ExceptionHelper.GetUnexpected();
            }

            await jvm.UpdateTask;
            return res;
        }`

**Comment by David-Desmaisons** [comment]
Use ChromiumFx + Ko bindings

**Comment by David-Desmaisons** [comment]
I am closing this issue as I will not provide update to new version of Awesomium. Please open dedicated issue on Neutronium if neded.
